import './globals.css';
import { cookies } from 'next/headers';
import { genURL } from '@/utils/swr';
import request from '@/utils/request/server';
import { API_URL } from '@/constants';
import { Providers } from './providers';

export const metadata = {
  title: 'Next Starter',
  description: 'Generated by create next app',
}

async function getUser(uid: number) {
  const res = await request(genURL(API_URL, uid), { cache: 'no-store' });
  return res;
}


export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies();
  const token: string | undefined = cookieStore.get('token')?.value;
  // Get common ui data on server side
  const user1: User | null = token ? (await getUser(1)) : null;
  const user2: User | null = token ? (await getUser(2)) : null;

  const swrFallback = { 
    [genURL(API_URL, 1)]: user1,
    [genURL(API_URL, 2)]: user2,
  };
  const initialState = { auth: { token }, swrFallback };

  return (
    <html lang="en">
      <body>
        <Providers initialState={initialState}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
